### ISSUE TITLE
Issue with stats.py

### ISSUE THREAD

**Issue by bpecsek** [ttsiodras/Score4#5]
I am trying to run the benchmark bu I am getting this:

```
$ make benchmark
make[1]: Entering directory '/home/bpecsek/Development/Benchmark/Score4/C++'
g++ -O3 -Wall -DNDEBUG -mtune=native -march=native -std=c++0x    score4.cpp   -o score4
g++ -O3 -Wall -DNDEBUG -mtune=native -march=native -std=c++0x    score4_extreme.cpp   -o score4_extreme
make[1]: Leaving directory '/home/bpecsek/Development/Benchmark/Score4/C++'
make[1]: Entering directory '/home/bpecsek/Development/Benchmark/Score4/C'
cc -O3 -Wall -DNDEBUG -mtune=native -march=native    score4.c   -o score4
make[1]: Leaving directory '/home/bpecsek/Development/Benchmark/Score4/C'
make[1]: Entering directory '/home/bpecsek/Development/Benchmark/Score4/Lisp'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/bpecsek/Development/Benchmark/Score4/Lisp'
make[1]: Entering directory '/home/bpecsek/Development/Benchmark/Score4/Rust'
cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
make[1]: Leaving directory '/home/bpecsek/Development/Benchmark/Score4/Rust'
make[1]: Entering directory '/home/bpecsek/Development/Benchmark/Score4/Java'
# I dont know how to compile "optimizations" for Java - help?
javac Score4.java
make[1]: Leaving directory '/home/bpecsek/Development/Benchmark/Score4/Java'
make[1]: Entering directory '/home/bpecsek/Development/Benchmark/Score4/OCaml'
ocamlopt -annot -unsafe -rectypes -inline 1000 -o ./score4.bin common.ml score4.ml
ocamlopt -annot -unsafe -rectypes -inline 1000 -o ./score4_functional.bin common.ml score4_functional.ml
make[1]: Leaving directory '/home/bpecsek/Development/Benchmark/Score4/OCaml'
make[1]: Entering directory '/home/bpecsek/Development/Benchmark/Score4/Go'
go build score4.go
make[1]: Leaving directory '/home/bpecsek/Development/Benchmark/Score4/Go'
make[1]: Entering directory '/home/bpecsek/Development/Benchmark/Score4/C#'
mcs -checked- -optimize+ -unsafe+ score4.cs
make[1]: Leaving directory '/home/bpecsek/Development/Benchmark/Score4/C#'
======================
= Running benchmarks =
======================
Benchmarking imperative memoized C++ ...Traceback (most recent call last):
  File "/home/bpecsek/Development/Benchmark/Score4/C++/../stats.py", line 18, in <module>
    print("Average value: %f" % (total/n))
ZeroDivisionError: division by zero
Benchmarking imperative C++ ...Traceback (most recent call last):
  File "/home/bpecsek/Development/Benchmark/Score4/C++/../stats.py", line 18, in <module>
    print("Average value: %f" % (total/n))
ZeroDivisionError: division by zero
Benchmarking imperative C ...Traceback (most recent call last):
  File "/home/bpecsek/Development/Benchmark/Score4/C/../stats.py", line 18, in <module>
    print("Average value: %f" % (total/n))
ZeroDivisionError: division by zero
Benchmarking imperative Lisp (SBCL) ...: 0.080000
    Finished release [optimized] target(s) in 0.00s
Benchmarking functional Rust ...Traceback (most recent call last):
  File "/home/bpecsek/Development/Benchmark/Score4/Rust/../stats.py", line 18, in <module>
    print("Average value: %f" % (total/n))
ZeroDivisionError: division by zero
Benchmarking imperative Java ...Traceback (most recent call last):
  File "/home/bpecsek/Development/Benchmark/Score4/Java/../stats.py", line 18, in <module>
    print("Average value: %f" % (total/n))
ZeroDivisionError: division by zero
Benchmarking imperative OCaml ...Traceback (most recent call last):
  File "/home/bpecsek/Development/Benchmark/Score4/OCaml/../stats.py", line 18, in <module>
    print("Average value: %f" % (total/n))
ZeroDivisionError: division by zero
Benchmarking functional OCaml ...Traceback (most recent call last):
  File "/home/bpecsek/Development/Benchmark/Score4/OCaml/../stats.py", line 18, in <module>
    print("Average value: %f" % (total/n))
ZeroDivisionError: division by zero
Benchmarking imperative Go ...Traceback (most recent call last):
  File "/home/bpecsek/Development/Benchmark/Score4/Go/../stats.py", line 18, in <module>
    print("Average value: %f" % (total/n))
ZeroDivisionError: division by zero
Benchmarking imperative C# ...Traceback (most recent call last):
  File "/home/bpecsek/Development/Benchmark/Score4/C#/../stats.py", line 18, in <module>
    print("Average value: %f" % (total/n))
ZeroDivisionError: division by zero
```

**Comment by ttsiodras** [comment]
Hi, @bpecsek .

Can you please try this?

In ~/Github/Score4
$ echo -e "1\n2\n3\n"
1
2
3

$ echo -e "1\n2\n3\n" | ./stats.py 
Average value: 2.000000
Std deviation: 0.816497
Median: 1.000000
Min: 1.000000
Max: 3.000000

**Comment by ttsiodras** [comment]
Hi @bpecsek .

I just pushed some changes in `stats.py` - maybe they will help.
Can you please test them on their own, with...

    $ echo -e "1\n2\n3\n"
    1
    2
    3

    $ echo -e "1\n2\n3\n" | ./stats.py
    Average value: 2.000000
    Std deviation: 0.816497
    Median: 2.000000
    Min: 1.000000
    Max: 3.000000

**Comment by bpecsek** [comment]
Results for above tests are correct but I am still getting the same error when running make benchmark (but now in line 19 of course).

**Comment by ttsiodras** [comment]
It also seems (from the "division by zero") that there are no outputs measured from the repeated executions, as if e.g. the compiled c++ executable didn't emit a single line. Try running it in isolation - e.g.

    $ cd C++
    $ time ./score4 o53 y43
    5

    real    0m0.091s
    user    0m0.091s
    sys     0m0.000s

Do you see output like this?
If not, since the benchmarking depends on the bash `time` builtin, see if `bash` is available.

**Comment by bpecsek** [comment]
Yes I do.

```
$ time ./score4 o53 y43
5

real	0m0,067s
user	0m0,067s
sys	0m0,000s
```

**Comment by ttsiodras** [comment]
OK - let's see if you are missing any other piece:

    $ make -n speedtest 
    bash -c 'for i in {1..10} ; do bash -c "time $BINARY o53 y43" 2>&1 ; done' | grep '^real' | sed 's,0m,,;s,s,,;' | awk '{print $2;}' | ../stats.py  | grep ^Min | sed 's,^Min,,'

    $ BINARY=./score4 bash -c 'for i in {1..10} ; do bash -c "time $BINARY o53 y43" 2>&1 ; done' | grep '^real' | sed 's,0m,,;s,s,,;' | awk '{print $2;}'
    0.084
    0.084
    0.084
    0.086
    0.084
    0.086
    0.084
    0.086
    0.085
    0.084

**Comment by bpecsek** [comment]
I am getting:

```
$ make -n speedtest
bash -c 'for i in {1..10} ; do bash -c "time $BINARY o53 y43" 2>&1 ; done' | grep '^real' | sed 's,0m,,;s,s,,;' | awk '{print $2;}' | ../stats.py  | grep ^Min | sed 's,^Min,,'

$ BINARY=./score4 bash -c 'for i in {1..10} ; do bash -c "time $BINARY o53 y43" 2>&1 ; done' | grep '^real' | sed 's,0m,,;s,s,,;' | awk '{print $2;}'0,063
0,058
0,059
0,059
0,058
0,058
0,058
0,058
0,058
0,061
```

**Comment by ttsiodras** [comment]
Ah! You get comma-separated output...

Can you prefix with LANG=C? i.e.

    $ LANG=C BINARY=./score4 bash -c 'for i in {1..10} ; do bash -c "time $BINARY o53 y43" 2>&1 ; done' | grep '^real' | sed 's,0m,,;s,s,,;' | awk '{print $2;}'0,063
0,058

**Comment by ttsiodras** [comment]
I pushed a commit that forces use of the C locale (that should force generation of "normal" floating point values).

**Comment by bpecsek** [comment]
I am still getting the same errors

**Comment by ttsiodras** [comment]
My bad, I should have used LC_NUMERIC not LANG. Can you confirm this emits numbers with dots instead of commas?

    LC_NUMERIC=C BINARY=./score4 bash -c 'for i in {1..10} ; do bash -c "time $BINARY o53 y43" 2>&1 ; done' | grep '^real' | sed 's,0m,,;s,s,,;' | awk '{print $2;}'

**Comment by bpecsek** [comment]
It does.

```
$ LC_NUMERIC=C BINARY=./score4 bash -c 'for i in {1..10} ; do bash -c "time $BINARY o53 y43" 2>&1 ; done' | grep '^real' | sed 's,0m,,;s,s,,;' | awk '{print $2;}'
0.061
0.059
0.058
0.058
0.059
0.058
0.059
0.058
0.058
0.059
```

Is it important to know that I am running the benchmark on Ubuntu Linux

**Comment by ttsiodras** [comment]
Then please try `git pull`-ing and `make benchmark` again. I hope this time it will work.

**Comment by bpecsek** [comment]
It did the trick!!!

```
======================
= Running benchmarks =
======================
Benchmarking imperative memoized C++ ...: 0.047000
Benchmarking imperative C++ ...: 0.058000
Benchmarking imperative C ...: 0.058000
Benchmarking imperative D ...: 0.079000
Benchmarking imperative Lisp (SBCL) ...: 0.080000
    Finished release [optimized] target(s) in 0.00s
Benchmarking functional Rust ...: 0.092000
Benchmarking imperative Java ...: 0.195000
Benchmarking imperative OCaml ...: 0.159000
Benchmarking functional OCaml ...: 0.329000
Benchmarking imperative Go ...: 0.278000
Benchmarking imperative C# ...: 0.370000
```
I shall try to speed up SBCL a bit to get closer to C++ speed.

**Comment by ttsiodras** [comment]
Thanks for reporting! I'd have never thought of time returning "invalid" numbers  :-)

And in case I didn't make it clear enough in the post ( https://www.thanassis.space/score4.html#lisp ) I absolutely love Lisp - any speedup will me most welcome. Ideally, create an "SBCL-speedup" branch, so we can keep the _"clean"_ macroexpanded version as well as whatever SBCL-specifics you do.

Closing - thanks again.

**Comment by bpecsek** [comment]
Clear!
Love Lisp too. Though it is just my hobby.
I am a mechanical engineer by trade and did my thesis in an AI field in the early 90' when Common Lisp was the language of choice for AI.
If you wanna see some of my benchmark optimizations (most of the CL program was improved by me except the first original version) you can have a look at the [Programming Language Benchmark](https://programming-language-benchmarks.vercel.app/problem/spectral-norm) site

**Comment by bpecsek** [comment]
One change in a single line and D is beaten:)
```
======================
= Running benchmarks =
======================
Benchmarking imperative memoized C++ ...: 0.047000
Benchmarking imperative C++ ...: 0.058000
Benchmarking imperative C ...: 0.058000
Benchmarking imperative D ...: 0.079000
Benchmarking imperative Lisp (SBCL) ...: 0.076000
    Finished release [optimized] target(s) in 0.00s
Benchmarking functional Rust ...: 0.092000
Benchmarking imperative Java ...: 0.181000
Benchmarking imperative OCaml ...: 0.159000
Benchmarking functional OCaml ...: 0.330000
Benchmarking imperative Go ...: 0.278000
Benchmarking imperative C# ...: 0.369000
```
